### PR TITLE
Sylvanie85/issue61

### LINKED ISSUE #61: Refactor function from module in the backend to catch errors and raise custom exceptions
## Issue Description

At present, several backend functions are not optimally handling exceptions. Some of them return `False` when they catch an exception, while others use the generic type `Exception` to catch all possible errors, which is not a good practice as it can hide critical errors that the team needs to address. Additionally, some custom exceptions are being attempted to be caught but are never raised in the first place.

Concerned module:

- azure_storage
- model_inference
  - inference.py
  - model_module.py
- model_request
- app.py

*Excluding pipelines_version_insertion.py as another [issue](https://github.com/ai-cfia/nachet-backend/issues/60) is specific to this case*

### Work to do

Refactor the backend to handle exceptions as per Python standards and provide meaningful error messages.

### Acceptance Criteria

- No more generic exceptions are caught or raised unless it is required (avoid server crash for example)
- When errors are caught in a module, the custom exception is raised with the `from` keyword when necessary

### Tasks

- [ ] Modify the azure_storage module to eliminate every return `False` from catching exception; raise a custom exception instead
- [x] Modify the model_inference module to catch specific exceptions and return the `ProcessInferenceResultError` custom error
- [ ] Raise a custom exception in model_request if the deployment platform of a model is not supported
- [x] Modify app.py to handle exceptions raised by the module it is using

### PR DESCRIPTION
**Pull request by sylvanie85**
I did some refactoring as my first issue on nachet-backend. 
The issue #61 was deprecated because the code has changed a lot since it was created. But I did make some fixes to the exception handling.

### CODE REVIEW

**Review by ChromaticPanic — CHANGES_REQUESTED** [review]
Can we move the Error class definitions into a separate module so that we are not redefining them in multiple files?

There is a custom_exceptions.py file

**Comment by Francois-Werbrouck** [comment]
> Can we move the Error class definitions into a separate module so that we are not redefining them in multiple files?
> 
> There is a custom_exceptions.py file

The issue this PR is based upon #61 which basically has the goal to remove the custom_exceptions file and redistribute the error to be module based instead

**Comment by ChromaticPanic** [comment]
> > Can we move the Error class definitions into a separate module so that we are not redefining them in multiple files?
> > There is a custom_exceptions.py file
> 
> The issue this PR is based upon #61 which basically has the goal to remove the custom_exceptions file and redistribute the error to be module based instead

That's okay for exceptions unique to a module, but some exceptions are shared. For example we do not redefine KeyError because that is something that is common.

For example the proposed approach has ApiErrors defined in multiple files. That seems wrong ~~on so many levels~~.

**Comment by ChromaticPanic** [comment]
> > Can we move the Error class definitions into a separate module so that we are not redefining them in multiple files?
> > There is a custom_exceptions.py file
> 
> The issue this PR is based upon #61 which basically has the goal to remove the custom_exceptions file and redistribute the error to be module based instead

I can elaborate on the issue as follows

Module 1 defines ApiError
Module 2 defines ApiError
Module 3 imports Module 1 and 2 and wants to handle the exceptions = name collision
There are also now 2 potential definitions of what ApiError means, when the reality is that they probably both refer to an issue with connecting an azure end point

Now if ApiError in Module 1 and 2 are in fact different but kinda related then they should inherit from a common parent ApiError but then they should have their own name

**Comment by Francois-Werbrouck** [comment]
> > > Can we move the Error class definitions into a separate module so that we are not redefining them in multiple files?
> > > There is a custom_exceptions.py file
> > 
> > 
> > The issue this PR is based upon #61 which basically has the goal to remove the custom_exceptions file and redistribute the error to be module based instead
> 
> That's okay for exceptions unique to a module, but some exceptions are shared. For example we do not redefine KeyError because that is something that is common.
> 
> For example the proposed approach has ApiErrors defined in multiple files. That seems wrong on so many levels.

Reviewing the changes I agree. The custom_exception file had too many exceptions in it, which are now module based. However defining APIErrors in 6+ files seems wrong.

**Review by Francois-Werbrouck — CHANGES_REQUESTED** [review]
Based on the discussion with @ChromaticPanic we should have a module to inherit the reccuring error Ex: `class ProcessInferenceResultsError(APIErrors) :`

**Comment by sylvanie85** [comment]
> Based on the discussion with @ChromaticPanic we should have a module to inherit the reccuring error Ex: `class ProcessInferenceResultsError(APIErrors) :`

So i need to create a new file to inherit the exception as was custom_exeptions ?

**Comment by ChromaticPanic** [comment]
> > Based on the discussion with @ChromaticPanic we should have a module to inherit the reccuring error Ex: `class ProcessInferenceResultsError(APIErrors) :`
> 
> So i need to create a new file to inherit the exception as was custom_exeptions ?

Yeah I would make that common ApiError

But also in each file I would use unique names for example in swin.py instead of ProcessInferenceResultsError(ApiError) I would name it SwinError(ApiError)  or SwinApiError (I don't know at this point how many error types will be thrown by each module)
Then it would work with the idea of having unique module errors defined in #61

**Review by Francois-Werbrouck — APPROVED** [review]
I like the new exception file and custom naming per module. I willl look into adapting the datastore to this standard!

LGTM! 👍🏻

**Review by ChromaticPanic — APPROVED** [review]

**Pull request merged**
